# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
            node-version: 14.x
            
      - name: Install node modules
        run: |
          yarn install

      - name: Run Pre-Commit with Lefthook
        run: |
          yarn lefthook run pre-merge

      - name: Run test
        run: |
          yarn test
